core/blog/urls.py
from django.urls import path

from django.views.generic import TemplateView
from .import views

app_name='blog'

urlpatterns = [
    path('post/',views.postlist.as_view(),name='list'),
    path('create/',views.createpost.as_view(),name='create'),
    path('detail/<int:pk>',views.detail_post.as_view(),name='detail1'),
    path('delet/<int:pk>',views.deletpost.as_view(),name='delet1')

]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

core/accunts/models.py
from django.db import models
from django.contrib.auth.models import(BaseUserManager,AbstractBaseUser,PermissionsMixin)
from django.db.models.signals import post_save
from django.dispatch import receiver
# from django.contrib.auth.models import(BaseUserManager,AbstractBaseUser,PermissionsMixin)
# from django.utils.translation import ugettext_lazy as _

# # Create your models here.


class UserManager(BaseUserManager):
    def create_user(self,email,password,**extra_fields):
        if not email:
          raise ValueError (('the email must be set'))
        email= self.normalize_email(email)
        user = self.model(email=email,**extra_fields)
        user.set_password(password)
        user.save()
        return user


    def create_superuser(self,email,password,**extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_superuser',True)
        extra_fields.setdefault('is_active',True)

        if extra_fields.get('is_staff') is not True :
            raise ValueError (_('is not true s staff'))
        
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('is not superuser true'))
        return self.create_user(email,password,**extra_fields)
        




class User(AbstractBaseUser,PermissionsMixin):

    '''
    custum user app

    '''
    
    email= models.EmailField(max_length=255,unique=True)
    is_superuser =models.BooleanField(default=False)
    is_staff=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)
    # is_verfied=models.BooleanField(default=False)
    firest_name=models.CharField(max_length=200)

    USERNAME_FIELD='email'

    REQUIRED_FIELDS=[]

    create_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)
    objects=UserManager()

    def __str__(self):
        return self.email

class Profile(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    firs_name=models.CharField(max_length=200)
    last_name=models.CharField(max_length=100)

    image=models.ImageField(blank=True,null=True)
    desc=models.TextField(max_length=500)
    creat_data=models.DateTimeField(auto_now_add=True)
    update_data=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email

@receiver(post_save,sender=User)

def save_profile(sender,instance,created,**kwoargs):
    if created:

     Profile.objects.create(user=instance)

core/blog/models.py
from django.db import models
from accunts.models import User
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    ''''
    thes class  for post app
    '''
    auhter=models.ForeignKey(User,on_delete=models.CASCADE)
    image=models.ImageField(null=True,blank=True)
    title=models.CharField(max_length=250)
    content=models.TextField()
    category=models.ForeignKey('Category',on_delete=models.SET_NULL,null=True)
    creat_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    name=models.CharField(max_length=25)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post

class Postform(forms.ModelForm):

    class Meta:
        model = Post
        fields= ['image','title','category']

core/accunts/views.py
from django.shortcuts import render

# Create your views here.

core/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,DeleteView, CreateView

from .models import Post
from .forms import Postform
# Create your views here.


class postlist(ListView):
    model=Post
    template_name='blog/index.html/'
    context_object_name='postlist'


class createpost(CreateView):
    model=Post
    fields=['image','title','category','auhter']
    success_url='/post/'

    def form_valid(self, form):
        form.instance.auhder=self.request.user
        return super().form_valid(form)



class detail_post(DetailView):
    model=Post


class deletpost(DeleteView):
    model=Post
    context_object_name='del'

    success_url='/post/'

core/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   {% for post in postlist %}
     <a href='{% url "blog:detail1" pk=post.id %}'><h1>{{ post.title }} </h1> </a>
     <a href="{% url 'blog:delet1' pk=post.id %}">delet</a>
     
   {% endfor %}
   <a href="{% url 'blog:create' %}">create</a>
   
  
</body>
</html>

core/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post"> {% csrf_token %}
        {{ del }}
        <input type="submit" value="save" >
    </form>
</body>
</html>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ object.title }}</h1>
    
</body>
</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save" >
    </form>
   
    
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    ,kjjk
</body>
</html>